# -*- coding: utf-8 -*-
"""Visualisation2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PDz-cpdXlKIFODX83SPT4IwHySjOG58F
"""

import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/train.csv')

print(df.columns)

# Plot histogram with KDE for car prices
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='Price', bins=30, kde=True)
plt.title('Distribution of Car Prices')
plt.xlabel('Price (in Lakhs)')
plt.ylabel('Number of Cars')
plt.grid(True)
plt.show()

# Count the number of cars for each fuel type
fuel_counts = df['Fuel_Type'].value_counts()

# Plot a pie chart for fuel types
plt.figure(figsize=(8, 8))
plt.pie(fuel_counts, labels=fuel_counts.index, autopct='%1.1f%%', startangle=140)
plt.title('Fuel Type Distribution')
plt.axis('equal')

# Clean the columns by extracting only the numeric part
df['Mileage'] = df['Mileage'].astype(str).str.extract(r'([\d.]+)').astype(float)
df['Engine'] = df['Engine'].astype(str).str.extract(r'([\d.]+)').astype(float)
df['Power'] = df['Power'].astype(str).str.extract(r'([\d.]+)').astype(float)

# Now recompute and plot the correlation heatmap
numerical_features = ['Price', 'Kilometers_Driven', 'Mileage', 'Engine', 'Power']
corr_matrix = df[numerical_features].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Correlation Heatmap of Selected Numerical Features')
plt.show()